[project]
name = "symplify"
version = "0.1.0"
description = "A modern symbolic calculator built with SymPy and PySide6 (QML)."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyside6>=6.11.1",
    "pyside6-fluentui-qml>=1.6.7",
    "pyyaml>=6.0.3",
    "sympy>=1.14.0",
    "ziamath>=0.13",
]
